### ISSUE TITLE
Create Navigation Menu

### ISSUE THREAD

**Issue by gitlherme** [wondertech-br/landing-page#2]
Figma para apoio: https://www.figma.com/file/6wxALZ7q2xljTIQ5yrBdR6/Wonder-Tech?node-id=0%3A1

# Tasks

- [ ] Criar Navigation Menu
- [ ] Criar Navigation Item
- [ ] Criar Drawer Mobile

## Mobile
![image](https://user-images.githubusercontent.com/37789845/167213746-f047f310-61aa-4e49-a59f-01e8fb9fcc2c.png)
### Ideia de como fazer
Utilizando o [Drawer](https://chakra-ui.com/docs/components/overlay/drawer) do ChakraUI

## Desktop
![image](https://user-images.githubusercontent.com/37789845/167213666-44c74469-23b3-49f9-bc38-0bfcf7b31383.png)
